version: 1.0.{build}
build_cloud: WIN-LKR467JS4GL
image: Windows
platform:
- x86
- x64
configuration:
- Release
install:
- cmd: git submodule -q update --init
- cmd: vcpkg integrate install
- cmd: vcpkg update
- ps: Setup-VS2022
before_build:
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\src\vīcĭus.vcxproj" --vcxproj.inf-time-stamp
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\src\vīcĭus.rc" --resource.file-version --resource.product-version
build:
  project: $(APPVEYOR_BUILD_FOLDER)\vīcĭus.sln
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true
